'use client';

import { formatCurrency } from '@/lib/utils';
import { RefundReportData, RefundReportHeaderInfo } from './types';

interface RefundReportContentProps {
    data: RefundReportData | null;
    loading?: boolean;
    headerInfo?: RefundReportHeaderInfo;
}

function SummaryCards({ data }: Readonly<{ data: RefundReportData }>) {
    const { summary } = data;
    const cards = [
        {
            label: 'Total Refund Count',
            value: String(summary.totalRefundCount),
        },
        {
            label: 'Total Refund Amount',
            value: formatCurrency(summary.totalRefundAmount),
        },
        {
            label: 'Average Refund Amount',
            value: formatCurrency(summary.averageRefundAmount),
        },
        {
            label: 'Number of Guests Refunded',
            value: String(summary.guestCount),
        },
    ];

    return (
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
            {cards.map((card) => (
                <div
                    key={card.label}
                    className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm"
                >
                    <p className="text-sm text-gray-600 mb-2">{card.label}</p>
                    <p className="text-2xl font-bold text-blue tabular-nums">
                        {card.value}
                    </p>
                </div>
            ))}
        </div>
    );
}

export default function RefundReportContent({
    data,
    loading = false,
    headerInfo,
}: Readonly<RefundReportContentProps>) {
    if (loading) {
        return (
            <div className="py-8">
                <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
                    {[1, 2, 3, 4].map((i) => (
                        <div
                            key={i}
                            className="h-24 bg-gray-100 rounded-lg animate-pulse"
                        />
                    ))}
                </div>
                <div className="h-64 bg-gray-100 rounded animate-pulse" />
            </div>
        );
    }

    if (!data) {
        return null;
    }

    return (
        <div className="py-8 max-w-full mx-auto">
            <div className="flex flex-col items-center mb-8 text-center px-2">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    Refund Report
                </h2>
                {headerInfo && (
                    <>
                        {headerInfo.hotelName && (
                            <p className="text-sm text-gray-600 mb-1">
                                {headerInfo.hotelName}
                            </p>
                        )}
                        <p className="text-sm text-gray-500 max-w-4xl leading-relaxed">
                            Printed At: {headerInfo.printedAt}
                            {' · '}
                            Report Period: {headerInfo.reportPeriod}
                            {' · '}
                            Payment: {headerInfo.paymentMethodLabel}
                            {' · '}
                            Refund account: {headerInfo.refundAccountLabel}
                            {' · '}
                            Staff: {headerInfo.staffLabel}
                            {' · '}
                            Generated By: {headerInfo.generatedBy}
                            {' · '}
                            Generated at: {headerInfo.generatedAt}
                        </p>
                    </>
                )}
            </div>

            {data.summary && <SummaryCards data={data} />}

            <div className="overflow-x-auto rounded-lg">
                <table className="w-full border-collapse rounded-lg overflow-hidden min-w-[1000px]">
                    <thead>
                        <tr className="bg-[#F4F4F4]">
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Date
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Time
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Guest Name
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Room / Type
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Stay Period
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Nights
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Opening Bal.
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Refund Amount
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Remaining Balance
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Processed By
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] whitespace-nowrap">
                                Payment Method
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] min-w-[180px]">
                                Refund From (Hotel Account)
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A] min-w-[140px]">
                                Reason
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.items.map((item, index) => (
                            <tr
                                key={`${item.date}-${item.time}-${item.guestName}-${index}`}
                                className="border-b border-gray-100 hover:bg-gray-50"
                            >
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] whitespace-nowrap">
                                    {item.date}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] whitespace-nowrap">
                                    {item.time}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.guestName}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.roomLabel}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] whitespace-nowrap">
                                    {item.stayPeriod}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right">
                                    {item.nights}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right whitespace-nowrap">
                                    {formatCurrency(item.openingBalance)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right whitespace-nowrap">
                                    {formatCurrency(item.refundAmount)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right whitespace-nowrap">
                                    {formatCurrency(item.remainingBalance)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.processedBy}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] whitespace-nowrap">
                                    {item.paymentMethod}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.refundFromAccount}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.reason}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {data.items.length === 0 && (
                <div className="text-center py-12 text-gray-500">
                    No refund transactions found for the selected filters.
                </div>
            )}
        </div>
    );
}
