// import { KotOverview } from './KotOverview';

// export const mockKotOrders: KotOverview[] = [
//     {
//         orderId: 'KOT-001',
//         orderTime: new Date('2024-03-20T12:30:00'),
//         orderType: 'Lunch',
//         date: new Date('2024-03-20'),
//         customerName: 'John Smith',
//         status: 'pending',
//         orderAmount: 45.5,
//         guestName: 'John Smith',
//         receivedBy: 'Sarah Johnson',
//         createdAt: new Date('2024-03-20T12:30:00'),
//         updatedAt: new Date('2024-03-20T12:30:00'),
//         orderItems: [
//             { itemName: 'Chicken Biryani', itemQuantity: 2 },
//             { itemName: 'Garlic Naan', itemQuantity: 4 },
//             { itemName: 'Mango Lassi', itemQuantity: 2 },
//         ],
//         notes: 'Extra spicy for the biryani',
//     },
//     {
//         orderId: 'KOT-002',
//         orderTime: new Date('2024-03-20T13:15:00'),
//         orderType: 'Dinner',
//         date: new Date('2024-03-20'),
//         customerName: 'Emily Brown',
//         status: 'preparing',
//         orderAmount: 78.25,
//         guestName: 'Emily Brown',
//         receivedBy: 'Michael Chen',
//         createdAt: new Date('2024-03-20T13:15:00'),
//         updatedAt: new Date('2024-03-20T13:15:00'),
//         orderItems: [
//             { itemName: 'Butter Chicken', itemQuantity: 1 },
//             { itemName: 'Vegetable Curry', itemQuantity: 1 },
//             { itemName: 'Plain Rice', itemQuantity: 2 },
//             { itemName: 'Gulab Jamun', itemQuantity: 2 },
//         ],
//         notes: 'No onions in the curry',
//     },
//     {
//         orderId: 'KOT-003',
//         orderTime: new Date('2024-03-20T14:00:00'),
//         orderType: 'Breakfast',
//         date: new Date('2024-03-20'),
//         customerName: 'David Wilson',
//         status: 'ready',
//         orderAmount: 32.75,
//         guestName: 'David Wilson',
//         receivedBy: 'Lisa Anderson',
//         createdAt: new Date('2024-03-20T14:00:00'),
//         updatedAt: new Date('2024-03-20T14:00:00'),
//         orderItems: [
//             { itemName: 'Masala Dosa', itemQuantity: 2 },
//             { itemName: 'Sambar', itemQuantity: 2 },
//             { itemName: 'Filter Coffee', itemQuantity: 2 },
//         ],
//         notes: 'Extra sambar on the side',
//     },
// ];
