'use client';

import { GuestInHouseReportData } from './types';

interface GuestInHouseReportContentProps {
    data: GuestInHouseReportData | null;
    loading?: boolean;
    headerInfo?: {
        hotelName?: string;
        printedAt: string;
        reportPeriod: string;
        roomType: string;
        generatedBy: string;
    };
}

function StatusBadge({ status }: { status: string }) {
    if (status === 'Checked Out') {
        return (
            <span className="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium bg-red-100 text-red-800">
                Checked Out
            </span>
        );
    }
    if (status === 'In-House') {
        return (
            <span className="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium bg-green-100 text-green-800">
                In-House
            </span>
        );
    }
    return (
        <span className="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium bg-gray-100 text-gray-700">
            Reserved
        </span>
    );
}

export default function GuestInHouseReportContent({
    data,
    loading = false,
    headerInfo,
}: Readonly<GuestInHouseReportContentProps>) {
    if (loading) {
        return (
            <div className="py-8">
                <div className="h-8 w-64 bg-gray-100 rounded animate-pulse mb-2 mx-auto" />
                <div className="h-4 w-96 bg-gray-100 rounded animate-pulse mb-8 mx-auto" />
                <div className="h-64 bg-gray-100 rounded animate-pulse" />
            </div>
        );
    }

    if (!data) return null;

    return (
        <div className="py-8 max-w-full mx-auto">
            <div className="flex flex-col items-center mb-8 text-center px-2">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    Guest List
                </h2>
                {headerInfo && (
                    <>
                        {headerInfo.hotelName && (
                            <p className="text-sm text-gray-600 mb-1">
                                {headerInfo.hotelName}
                            </p>
                        )}
                        <p className="text-sm text-gray-500 max-w-4xl leading-relaxed">
                            Printed At: {headerInfo.printedAt}
                            {' · '}
                            Report Period: {headerInfo.reportPeriod}
                            {' · '}
                            Room type: {headerInfo.roomType}
                            {' · '}
                            Generated By: {headerInfo.generatedBy}
                        </p>
                    </>
                )}
            </div>

            <div className="overflow-x-auto rounded-lg">
                <table className="w-full border-collapse rounded-lg overflow-hidden min-w-[1100px]">
                    <thead>
                        <tr className="bg-[#F4F4F4]">
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Res. No
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Guest Name
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Room Num /type
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Arrival Date
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Departure Date
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Night
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Pax
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Created By
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Status
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.items.map((item, index) => (
                            <tr
                                key={`${item.reservationNo}-${index}`}
                                className="border-b border-gray-100 hover:bg-gray-50"
                            >
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.reservationNo}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.guestName}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.roomLabel}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.arrivalDate}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.departureDate}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.nights}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.pax}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.createdBy}
                                </td>
                                <td className="py-4 px-2 text-[14px]">
                                    <StatusBadge status={item.status} />
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {data.items.length === 0 && (
                <div className="text-center py-12 text-gray-500">
                    No guest records found for the selected filters.
                </div>
            )}

            {data.items.length > 0 && headerInfo && (
                <p className="text-center text-sm text-orange-600 mt-6">
                    Generated {headerInfo.printedAt} · Created by{' '}
                    {headerInfo.generatedBy}
                </p>
            )}
        </div>
    );
}
