'use client';

import { format } from 'date-fns';

interface PostedBillsRegisterReportProps {
  data: any[];
  businessName: string;
  businessAddress: string;
  businessPhone: string;
  businessDate: string;
  workPeriodId: string | number;
  generatedAt: string;
  generatedBy: string;
  loading?: boolean;
}

export default function PostedBillsRegisterReport({
  data,
  businessName,
  businessAddress,
  businessPhone,
  businessDate,
  workPeriodId,
  generatedAt,
  generatedBy,
  loading = false,
}: PostedBillsRegisterReportProps) {
  if (loading) {
    return (
      <div className="py-8">
        <div className="flex flex-col items-center gap-4">
          <div className="h-6 w-64 bg-gray-100 rounded animate-pulse" />
          <div className="h-4 w-48 bg-gray-100 rounded animate-pulse" />
          <div className="h-32 w-full max-w-2xl bg-gray-100 rounded animate-pulse mt-6" />
        </div>
      </div>
    );
  }

  const totalAmount = data.reduce(
    (sum, row) => sum + Number(row.totalPrice || 0),
    0,
  );

  return (
    <div className="py-6 max-w-6xl mx-auto">
      <div className=" rounded-lg p-6 text-sm print:border-0 print:shadow-none">
        <div className="text-center mb-4">
          <div className="font-bold uppercase tracking-wide text-lg">
            {businessName}
          </div>
          {businessAddress && (
            <div className="text-muted-foreground text-xs mt-0.5">
              {businessAddress}
            </div>
          )}
          {businessPhone && (
            <div className="text-muted-foreground text-xs">
              {businessPhone}
            </div>
          )}
          <div className="font-semibold mt-3 text-base">
            Posted Room Bills Register
          </div>
          <div className="text-muted-foreground text-xs mt-1">
            Business Date: {businessDate} | Work Period ID: {workPeriodId}
          </div>
        </div>

        <hr className="border-dashed border-gray-300 my-3 print:my-1" />

        <div className="mb-3 print:mb-1">
          <div className="font-semibold mb-1">Report Metadata</div>
          <div className="grid grid-cols-2 gap-1 text-xs">
            <span className="text-muted-foreground">Generated Date &amp; Time:</span>
            <span>{generatedAt}</span>
            <span className="text-muted-foreground">Generated By:</span>
            <span>{generatedBy}</span>
          </div>
        </div>

        <hr className="border-dashed border-gray-300 my-3 print:my-1" />

        <div className="overflow-x-auto">
          <table className="w-full table-fixed border-collapse">
            <thead>
              <tr className="bg-gray-100 border-b border-gray-300">
                <th className="py-1 px-2 text-left text-xs font-semibold w-8">#</th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Order ID
                </th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Date
                </th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Guest Name
                </th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Room
                </th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Order Type
                </th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Waiter
                </th>
                <th className="py-1 px-2 text-right text-xs font-semibold">
                  Amount
                </th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Payment Status
                </th>
                <th className="py-1 px-2 text-left text-xs font-semibold">
                  Status
                </th>
              </tr>
            </thead>
            <tbody>
              {data.length === 0 && (
                <tr>
                  <td
                    colSpan={10}
                    className="py-4 text-center text-muted-foreground text-xs"
                  >
                    No posted room bills found for the selected period.
                  </td>
                </tr>
              )}
              {data.map((row, index) => (
                <tr
                  key={row.id}
                  className="border-b border-gray-100 hover:bg-gray-50"
                >
                  <td className="py-1 px-2 text-xs tabular-nums">
                    {index + 1}
                  </td>
                  <td className="py-1 px-2 text-xs">
                    {row.requestId || `#${row.id}`}
                  </td>
                  <td className="py-1 px-2 text-xs">
                    {format(new Date(row.createdAt), 'MMM d, yyyy h:mm a')}
                  </td>
                  <td className="py-1 px-2 text-xs">{row.guestName || '—'}</td>
                  <td className="py-1 px-2 text-xs">
                    Room-{row.room?.roomNumber || '—'}
                  </td>
                  <td className="py-1 px-2 text-xs">{row.orderType}</td>
                  <td className="py-1 px-2 text-xs">
                    {row.waiter?.fullName || row.createdBy?.fullName || '—'}
                  </td>
                  <td className="py-1 px-2 text-xs text-right tabular-nums">
                    {Number(row.totalPrice).toLocaleString('en-NG', {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    })}
                  </td>
                  <td className="py-1 px-2 text-xs">
                    <span
                      className={`inline-block px-2 py-0.5 rounded-full text-xs ${
                        row.paymentStatus === 'ADDED_TO_BILL'
                          ? 'bg-amber-100 text-amber-700'
                          : row.paymentStatus === 'BILL_SETTLED_FROM_FRONT_DESK'
                          ? 'bg-blue-100 text-blue-700'
                          : row.paymentStatus === 'PAID'
                          ? 'bg-green-100 text-green-700'
                          : 'bg-yellow-100 text-yellow-700'
                      }`}
                    >
                      {row.paymentStatus === 'BILL_SETTLED_FROM_FRONT_DESK'
                        ? 'Bill Settled from Front Desk'
                        : row.paymentStatus === 'ADDED_TO_BILL'
                        ? 'Added to Bill'
                        : row.paymentStatus}
                    </span>
                  </td>
                  <td className="py-1 px-2 text-xs">{row.status}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="border-t-2 border-gray-300 bg-gray-50">
                <td
                  colSpan={7}
                  className="py-1 px-2 text-xs font-semibold text-right"
                >
                  Total:
                </td>
                <td className="py-1 px-2 text-xs font-bold tabular-nums">
                  {totalAmount.toLocaleString('en-NG', {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2,
                  })}
                </td>
                <td colSpan={2} />
              </tr>
              <tr>
                <td
                  colSpan={7}
                  className="py-1 px-2 text-xs font-semibold text-right"
                >
                  Total Orders:
                </td>
                <td
                  colSpan={3}
                  className="py-1 px-2 text-xs font-bold tabular-nums"
                >
                  {data.length}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>

        <hr className="border-dashed border-gray-300 my-3 print:my-1" />

        <div className="flex flex-wrap justify-between text-xs text-muted-foreground mt-2">
          <span>Printed: {generatedAt}</span>
          <span>By: {generatedBy}</span>
          <span>Work Period ID: {workPeriodId}</span>
        </div>
      </div>
    </div>
  );
}