import { BanquetReportRow } from './types';

export const BOOKING_SUMMARY_ROWS: BanquetReportRow[] = [
    {
        bookingId: 'BK-2025-001',
        customerName: 'Tolu Weddings Ltd',
        eventType: 'Wedding',
        eventDate: '12 Jun 2025',
        venue: 'Grand Hall',
        guests: 500,
        bookingStatus: 'Confirmed',
        paymentStatus: 'Partially Paid',
        totalAmount: '₦4,500,000',
        coordinator: 'Anita George',
    },
    {
        bookingId: 'BK-2025-002',
        customerName: 'Zenith Energy',
        eventType: 'Corporate Conference',
        eventDate: '18 Jun 2025',
        venue: 'Emerald Hall',
        guests: 180,
        bookingStatus: 'Completed',
        paymentStatus: 'Paid',
        totalAmount: '₦2,150,000',
        coordinator: 'Daniel Peters',
    },
    {
        bookingId: 'BK-2025-003',
        customerName: 'Grace Ministries',
        eventType: 'Church Program',
        eventDate: '25 Jun 2025',
        venue: 'Royal Hall',
        guests: 350,
        bookingStatus: 'Pending',
        paymentStatus: 'Awaiting Payment',
        totalAmount: '₦1,200,000',
        coordinator: 'Faith Johnson',
    },
];

export const REVENUE_ROWS: BanquetReportRow[] = [
    {
        invoiceId: 'INV-1001',
        bookingId: 'BK-2025-001',
        customer: 'Tolu Weddings Ltd',
        eventType: 'Wedding',
        paymentDate: '01 Jun 2025',
        paymentMethod: 'Bank Transfer',
        amountPaid: '₦2,500,000',
        outstandingBalance: '₦2,000,000',
        tax: '₦187,500',
        totalRevenue: '₦4,500,000',
    },
    {
        invoiceId: 'INV-1002',
        bookingId: 'BK-2025-002',
        customer: 'Zenith Energy',
        eventType: 'Conference',
        paymentDate: '15 Jun 2025',
        paymentMethod: 'POS',
        amountPaid: '₦2,150,000',
        outstandingBalance: '₦0',
        tax: '₦96,750',
        totalRevenue: '₦2,150,000',
    },
    {
        invoiceId: 'INV-1003',
        bookingId: 'BK-2025-003',
        customer: 'Grace Ministries',
        eventType: 'Church Event',
        paymentDate: '20 Jun 2025',
        paymentMethod: 'Cash',
        amountPaid: '₦500,000',
        outstandingBalance: '₦700,000',
        tax: '₦54,000',
        totalRevenue: '₦1,200,000',
    },
];

export const OUTSTANDING_PAYMENT_ROWS: BanquetReportRow[] = [
    {
        bookingId: 'BK-2025-001',
        customer: 'Tolu Weddings Ltd',
        eventDate: '12 Jun 2025',
        totalInvoice: '₦4,500,000',
        amountPaid: '₦2,500,000',
        outstandingBalance: '₦2,000,000',
        dueDate: '10 Jun 2025',
        paymentStatus: 'Partial',
        followUpStatus: 'Reminder Sent',
    },
    {
        bookingId: 'BK-2025-003',
        customer: 'Grace Ministries',
        eventDate: '25 Jun 2025',
        totalInvoice: '₦1,200,000',
        amountPaid: '₦500,000',
        outstandingBalance: '₦700,000',
        dueDate: '22 Jun 2025',
        paymentStatus: 'Outstanding',
        followUpStatus: 'Pending Follow-up',
    },
    {
        bookingId: 'BK-2025-007',
        customer: 'Bright Future School',
        eventDate: '29 Jun 2025',
        totalInvoice: '₦850,000',
        amountPaid: '₦300,000',
        outstandingBalance: '₦550,000',
        dueDate: '27 Jun 2025',
        paymentStatus: 'Partial',
        followUpStatus: 'Escalated',
    },
];

export const EVENT_CALENDAR_ROWS: BanquetReportRow[] = [
    {
        eventId: 'EVT-001',
        eventName: 'Johnson Wedding',
        eventType: 'Wedding',
        customer: 'Johnson Family',
        eventDate: '12 Jun 2025',
        startTime: '10:00 AM',
        endTime: '08:00 PM',
        venue: 'Grand Hall',
        coordinator: 'Anita George',
        status: 'Confirmed',
    },
    {
        eventId: 'EVT-002',
        eventName: 'Annual Sales Summit',
        eventType: 'Corporate',
        customer: 'Zenith Energy',
        eventDate: '18 Jun 2025',
        startTime: '09:00 AM',
        endTime: '05:00 PM',
        venue: 'Emerald Hall',
        coordinator: 'Daniel Peters',
        status: 'Completed',
    },
    {
        eventId: 'EVT-003',
        eventName: 'Youth Revival',
        eventType: 'Church Program',
        customer: 'Grace Ministries',
        eventDate: '25 Jun 2025',
        startTime: '04:00 PM',
        endTime: '10:00 PM',
        venue: 'Royal Hall',
        coordinator: 'Faith Johnson',
        status: 'Pending',
    },
];

export const MENU_PACKAGE_PERFORMANCE_ROWS: BanquetReportRow[] = [
    {
        packageId: 'MP-001',
        packageName: 'Royal Wedding Buffet',
        category: 'Buffet',
        timesBooked: 28,
        averageGuests: 450,
        revenueGenerated: '₦18,500,000',
        mostCommonEventType: 'Wedding',
        status: 'Active',
    },
    {
        packageId: 'MP-002',
        packageName: 'Executive Corporate Menu',
        category: 'Plated',
        timesBooked: 16,
        averageGuests: 180,
        revenueGenerated: '₦7,200,000',
        mostCommonEventType: 'Conference',
        status: 'Active',
    },
    {
        packageId: 'MP-003',
        packageName: 'Premium Small Chops',
        category: 'Add-on',
        timesBooked: 34,
        averageGuests: 120,
        revenueGenerated: '₦3,850,000',
        mostCommonEventType: 'Birthday',
        status: 'Active',
    },
];

export const AMENITIES_INVENTORY_ROWS: BanquetReportRow[] = [
    {
        amenityId: 'AM-001',
        amenityName: 'Sound System',
        category: 'Audio',
        totalQuantity: 10,
        availableQuantity: 4,
        rentedQuantity: 6,
        condition: 'Excellent',
        dailyRentalFee: '₦25,000',
        status: 'Active',
    },
    {
        amenityId: 'AM-002',
        amenityName: 'Round Tables',
        category: 'Furniture',
        totalQuantity: 120,
        availableQuantity: 45,
        rentedQuantity: 75,
        condition: 'Good',
        dailyRentalFee: '₦2,500',
        status: 'Active',
    },
    {
        amenityId: 'AM-003',
        amenityName: 'LED Wall Screen',
        category: 'Visual Equipment',
        totalQuantity: 4,
        availableQuantity: 1,
        rentedQuantity: 3,
        condition: 'Good',
        dailyRentalFee: '₦80,000',
        status: 'Maintenance',
    },
];

export const AMENITY_RENTAL_REVENUE_ROWS: BanquetReportRow[] = [
    {
        rentalId: 'RENT-001',
        amenity: 'Sound System',
        customer: 'Tolu Weddings Ltd',
        eventType: 'Wedding',
        rentalPeriod: '2 Days',
        quantity: 2,
        rentalFee: '₦50,000',
        deliveryFee: '₦10,000',
        totalRevenue: '₦60,000',
        returnStatus: 'Returned',
    },
    {
        rentalId: 'RENT-002',
        amenity: 'LED Wall Screen',
        customer: 'Zenith Energy',
        eventType: 'Conference',
        rentalPeriod: '1 Day',
        quantity: 1,
        rentalFee: '₦80,000',
        deliveryFee: '₦15,000',
        totalRevenue: '₦95,000',
        returnStatus: 'Active',
    },
    {
        rentalId: 'RENT-003',
        amenity: 'Plastic Chairs',
        customer: 'Grace Ministries',
        eventType: 'Church Program',
        rentalPeriod: '3 Days',
        quantity: 200,
        rentalFee: '₦120,000',
        deliveryFee: '₦20,000',
        totalRevenue: '₦140,000',
        returnStatus: 'Overdue',
    },
];

export const OVERDUE_RETURNS_ROWS: BanquetReportRow[] = [
    {
        rentalId: 'RENT-003',
        amenity: 'Plastic Chairs',
        customer: 'Grace Ministries',
        dueReturnDate: '26 Jun 2025',
        daysOverdue: '3 Days',
        quantity: 200,
        penaltyFee: '₦15,000',
        contactPerson: 'Pastor David',
        phoneNumber: '+234 803 456 8890',
        status: 'Pending Return',
    },
    {
        rentalId: 'RENT-006',
        amenity: 'Wireless Microphones',
        customer: 'Bright Future School',
        dueReturnDate: '20 Jun 2025',
        daysOverdue: '5 Days',
        quantity: 6,
        penaltyFee: '₦25,000',
        contactPerson: 'Mrs. Helen James',
        phoneNumber: '+234 812 445 9921',
        status: 'Escalated',
    },
    {
        rentalId: 'RENT-008',
        amenity: 'Projector Screen',
        customer: 'Kings Conference Ltd',
        dueReturnDate: '22 Jun 2025',
        daysOverdue: '2 Days',
        quantity: 1,
        penaltyFee: '₦8,000',
        contactPerson: 'Samuel Obi',
        phoneNumber: '+234 701 234 8871',
        status: 'Reminder Sent',
    },
];

export const CUSTOMER_BOOKING_HISTORY_ROWS: BanquetReportRow[] = [
    {
        customerName: 'Tolu Weddings Ltd',
        totalBookings: 8,
        firstBookingDate: '12 Jan 2024',
        lastBookingDate: '12 Jun 2025',
        mostFrequentEventType: 'Wedding',
        totalSpend: '₦24,500,000',
        outstandingBalance: '₦2,000,000',
        customerStatus: 'VIP',
    },
    {
        customerName: 'Zenith Energy',
        totalBookings: 5,
        firstBookingDate: '08 Mar 2024',
        lastBookingDate: '18 Jun 2025',
        mostFrequentEventType: 'Conference',
        totalSpend: '₦11,200,000',
        outstandingBalance: '₦0',
        customerStatus: 'Active',
    },
    {
        customerName: 'Grace Ministries',
        totalBookings: 3,
        firstBookingDate: '20 Aug 2024',
        lastBookingDate: '25 Jun 2025',
        mostFrequentEventType: 'Church Program',
        totalSpend: '₦3,900,000',
        outstandingBalance: '₦700,000',
        customerStatus: 'Active',
    },
];

export const BUSINESS_PERFORMANCE_ROWS: BanquetReportRow[] = [
    {
        reportingPeriod: 'January 2025',
        totalBookings: 48,
        completedEvents: 41,
        totalRevenue: '₦18,500,000',
        outstandingPayments: '₦2,100,000',
        totalCustomers: 39,
        mostPopularEventType: 'Wedding',
        occupancyRate: '72%',
    },
    {
        reportingPeriod: 'February 2025',
        totalBookings: 53,
        completedEvents: 49,
        totalRevenue: '₦22,700,000',
        outstandingPayments: '₦1,450,000',
        totalCustomers: 44,
        mostPopularEventType: 'Conference',
        occupancyRate: '81%',
    },
    {
        reportingPeriod: 'March 2025',
        totalBookings: 61,
        completedEvents: 55,
        totalRevenue: '₦28,900,000',
        outstandingPayments: '₦3,200,000',
        totalCustomers: 52,
        mostPopularEventType: 'Wedding',
        occupancyRate: '89%',
    },
];
