'use client';

import { ColumnDef } from '@tanstack/react-table';
import { SalesLog } from './types';
import { formatCurrency } from '@/lib/utils';
import { format } from 'date-fns';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

export const getSalesLogColumns = (router: any): ColumnDef<SalesLog>[] => [
    {
        accessorKey: 'date',
        header: 'Date',
        cell: ({ row }) => {
            const date = new Date(row.original.date || row.original.createdAt);
            return (
                <span className="font-medium">
                    {format(date, 'dd MMM yyyy')}
                </span>
            );
        },
    },
    {
        accessorKey: 'logId',
        header: 'Log ID',
    },
    {
        accessorKey: 'totalMenuItemsSold',
        header: 'Menu Items',
    },
    {
        accessorKey: 'totalItemsUsed',
        header: 'Items Used',
    },
    {
        accessorKey: 'totalInventoryValueUsed',
        header: 'Total Value',
        cell: ({ row }) =>
            formatCurrency(Number(row.original.totalInventoryValueUsed || 0)),
    },
    {
        accessorKey: 'generatedBy',
        header: 'Generated By',
        cell: ({ row }: any) => {
            if (row.original.isAutoGenerated) return 'System';
            return (
                row.original.generatedBy?.fullName ||
                row.original.generatedBy ||
                'N/A'
            );
        },
    },
    {
        accessorKey: 'reviewedBy',
        header: 'Reviewed By',
        cell: ({ row }: any) =>
            row.original.reviewedBy?.fullName ||
            row.original.reviewedBy ||
            '---',
    },
    {
        accessorKey: 'status',
        header: 'Status',
        cell: ({ row }) => {
            const status = row.original.status as string;
            return (
                <Badge
                    className={cn(
                        'capitalize font-normal rounded-full px-2 py-0.5',
                        status?.toUpperCase() === 'DRAFT' &&
                            'bg-orange-100 text-orange-600 hover:bg-orange-100 shadow-none border-none',
                        status?.toUpperCase() === 'REVIEWED' &&
                            'bg-blue-100 text-blue-600 hover:bg-blue-100 shadow-none border-none',
                        status?.toUpperCase() === 'PRINTED' &&
                            'bg-green-100 text-green-600 hover:bg-green-100 shadow-none border-none',
                    )}
                >
                    {status}
                </Badge>
            );
        },
    },
    {
        id: 'actions',
        header: 'Action',
        cell: ({ row }) => {
            return (
                <div className="flex items-center gap-3">
                    <button className="text-orion-blue text-sm hover:underline">
                        Print
                    </button>
                    <button
                        className="text-orion-blue text-sm hover:underline"
                        onClick={() =>
                            router.push(`/stock/sales-log/${row.original.id}`)
                        }
                    >
                        View
                    </button>
                </div>
            );
        },
    },
];
