export interface SalesLog {
    id: number;
    logId: string;
    date: string;
    totalMenuItemsSold: number;
    totalItemsUsed: number;
    totalInventoryValueUsed: number;
    generatedBy: any;
    reviewedBy?: any;
    status: 'DRAFT' | 'REVIEWED' | 'PRINTED' | string;
    isAutoGenerated: boolean;
    createdAt: string;
}

export interface SalesLogDetailIngredient {
    id: number;
    name: string;
    quantityUsed: number;
    unit: string;
    costPerUnit: number;
    totalValue: number;
}

export interface SalesLogDetailMenuItem {
    id: number;
    name: string;
    quantity: number;
    ingredients: SalesLogDetailIngredient[];
}

export interface SalesLogDetail extends SalesLog {
    menuItems: SalesLogDetailMenuItem[];
    manualItems: any[];
    manualItemsAdded: number;
}
