'use client';

import { NoShowReportData } from './types';

interface NoShowReportContentProps {
    data: NoShowReportData | null;
    loading?: boolean;
    headerInfo?: {
        hotelName?: string;
        printedAt: string;
        reportPeriod: string;
        roomType: string;
        generatedBy: string;
    };
}

export default function NoShowReportContent({
    data,
    loading = false,
    headerInfo,
}: Readonly<NoShowReportContentProps>) {
    if (loading) {
        return (
            <div className="py-8">
                <div className="h-8 w-64 bg-gray-100 rounded animate-pulse mb-2 mx-auto" />
                <div className="h-4 w-96 bg-gray-100 rounded animate-pulse mb-8 mx-auto" />
                <div className="h-64 bg-gray-100 rounded animate-pulse" />
            </div>
        );
    }

    if (!data) return null;

    return (
        <div className="py-8 max-w-full mx-auto">
            <div className="flex flex-col items-center mb-8 text-center px-2">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    No-Show Report
                </h2>
                {headerInfo && (
                    <>
                        {headerInfo.hotelName && (
                            <p className="text-sm text-gray-600 mb-1">
                                {headerInfo.hotelName}
                            </p>
                        )}
                        <p className="text-sm text-gray-500 max-w-4xl leading-relaxed">
                            Printed At: {headerInfo.printedAt}
                            {' · '}
                            Report Period: {headerInfo.reportPeriod}
                            {' · '}
                            Room type: {headerInfo.roomType}
                            {' · '}
                            Generated By: {headerInfo.generatedBy}
                        </p>
                    </>
                )}
            </div>

            <div className="overflow-x-auto rounded-lg">
                <table className="w-full border-collapse rounded-lg overflow-hidden min-w-[1200px]">
                    <thead>
                        <tr className="bg-[#F4F4F4]">
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Res. No
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Room Num / type
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Guest Name
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Booking Date
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Adult
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Child
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Created By
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                No-Show Date
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Marked By
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Reason
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.items.map((item, index) => (
                            <tr
                                key={`${item.reservationNo}-${index}`}
                                className="border-b border-gray-100 hover:bg-gray-50"
                            >
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.reservationNo}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.roomLabel}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.guestName}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.bookingDate}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.adult}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.child}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.createdBy}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.noShowDate}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.markedBy}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.reason}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {data.items.length === 0 && (
                <div className="text-center py-12 text-gray-500">
                    No no-show records found for the selected filters.
                </div>
            )}
        </div>
    );
}
