'use client';

import { formatCurrency } from '@/lib/utils';
import { AccountReceivableSummaryData } from './types';

interface AccountReceivableSummaryContentProps {
    data: AccountReceivableSummaryData | null;
    loading?: boolean;
    headerInfo?: {
        hotelName?: string;
        printedAt: string;
        reportPeriod: string;
        generatedBy: string;
    };
}

export default function AccountReceivableSummaryContent({
    data,
    loading = false,
    headerInfo,
}: Readonly<AccountReceivableSummaryContentProps>) {
    if (loading) {
        return (
            <div className="py-8">
                <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
                    {[1, 2, 3, 4].map((i) => (
                        <div
                            key={i}
                            className="h-24 bg-gray-100 rounded-lg animate-pulse"
                        />
                    ))}
                </div>
                <div className="h-64 bg-gray-100 rounded animate-pulse" />
            </div>
        );
    }

    if (!data) return null;

    return (
        <div className="py-8 max-w-full mx-auto">
            <div className="flex flex-col items-center mb-8 text-center px-2">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    Account Receivable Summary Report
                </h2>
                {headerInfo && (
                    <>
                        {headerInfo.hotelName && (
                            <p className="text-sm text-gray-600 mb-1">
                                {headerInfo.hotelName}
                            </p>
                        )}
                        <p className="text-sm text-gray-500 max-w-4xl leading-relaxed">
                            Printed At: {headerInfo.printedAt}
                            {' · '}
                            Report Period: {headerInfo.reportPeriod}
                            {' · '}
                            Generated By: {headerInfo.generatedBy}
                        </p>
                    </>
                )}
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
                <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
                    <p className="text-sm text-gray-600 mb-2">
                        Total Receivables
                    </p>
                    <p className="text-2xl font-bold text-blue tabular-nums">
                        {data.summary.totalReceivableCount}
                    </p>
                </div>
                <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
                    <p className="text-sm text-gray-600 mb-2">
                        Total Outstanding
                    </p>
                    <p className="text-2xl font-bold text-blue tabular-nums">
                        {formatCurrency(data.summary.totalOutstanding)}
                    </p>
                </div>
                <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
                    <p className="text-sm text-gray-600 mb-2">Total Paid</p>
                    <p className="text-2xl font-bold text-blue tabular-nums">
                        {formatCurrency(data.summary.totalAmountPaid)}
                    </p>
                </div>
                <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
                    <p className="text-sm text-gray-600 mb-2">Guests</p>
                    <p className="text-2xl font-bold text-blue tabular-nums">
                        {data.summary.guestCount}
                    </p>
                </div>
            </div>

            <div className="overflow-x-auto rounded-lg">
                <table className="w-full border-collapse rounded-lg overflow-hidden min-w-[1100px]">
                    <thead>
                        <tr className="bg-[#F4F4F4]">
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Date
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Time
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Res. No
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Guest Name
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Room Number
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Room Type
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold">
                                Opening Balance
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold">
                                Amount Paid
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold">
                                Outstanding
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Created By
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold">
                                Status
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.items.map((item, index) => (
                            <tr
                                key={`${item.reservationNo}-${item.guestName}-${index}`}
                                className="border-b border-gray-100 hover:bg-gray-50"
                            >
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.date}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.time}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.reservationNo}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.guestName}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.roomNumber}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.roomType}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-right text-[#7B7878]">
                                    {formatCurrency(item.openingBalance)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-right text-[#7B7878]">
                                    {formatCurrency(item.amountPaid)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-right text-[#7B7878]">
                                    {formatCurrency(item.outstandingBalance)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.createdBy}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.status}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {data.items.length === 0 && (
                <div className="text-center py-12 text-gray-500">
                    No receivables found for the selected filters.
                </div>
            )}
        </div>
    );
}
