import { Reservation } from './types';

export const SAMPLE_RESERVATIONS: Reservation[] = [
    {
        id: '1',
        name: 'Tobi Eli',
        tableNum: 105,
        partySize: 'single RSV',
        status: 'pending',
        startTime: '09:00',
        endTime: '10:30',
        date: '2025-08-24',
    },
    {
        id: '2',
        name: 'Martin Els',
        tableNum: 105,
        partySize: 'single RSV',
        status: 'paid',
        startTime: '09:00',
        endTime: '10:00',
        date: '2025-08-26',
    },
    {
        id: '3',
        name: 'Tochi Ada',
        tableNum: 105,
        partySize: 'single RSV',
        status: 'pending',
        startTime: '11:00',
        endTime: '13:00',
        date: '2025-08-25',
    },
    {
        id: '4',
        name: 'Tony Ali',
        tableNum: 105,
        partySize: 'single RSV',
        status: 'paid',
        startTime: '11:00',
        endTime: '12:30',
        date: '2025-08-27',
    },
    {
        id: '5',
        name: 'Benjamin Udo',
        tableNum: 105,
        partySize: 'single RSV',
        status: 'paid',
        startTime: '13:00',
        endTime: '15:00',
        date: '2025-08-24',
    },
    {
        id: '6',
        name: 'Goodness Ego',
        tableNum: 102,
        partySize: '2 guests',
        status: 'paid',
        startTime: '14:00',
        endTime: '16:00',
        date: '2025-08-28',
    },
    {
        id: '7',
        name: 'Goodness Ego',
        tableNum: 102,
        partySize: '2 guests',
        status: 'paid',
        startTime: '9:00',
        endTime: '10:30',
        date: '2026-01-06',
    },
    {
        id: '8',
        name: 'Goodness Ego',
        tableNum: 102,
        partySize: '2 guests',
        status: 'pending',
        startTime: '10:00',
        endTime: '12:00',
        date: '2026-01-07',
    },
    {
        id: '9',
        name: 'Goodness Ego',
        tableNum: 102,
        partySize: '2 guests',
        status: 'paid',
        startTime: '11:00',
        endTime: '1:00',
        date: '2026-01-08',
    },
];
