'use client';

import { formatCurrency } from '@/lib/utils';
import { SalesReportData, SalesReportHeaderInfo } from './types';

interface SalesReportContentProps {
    data: SalesReportData | null;
    loading?: boolean;
    headerInfo?: SalesReportHeaderInfo;
}

function KpiCard({
    label,
    value,
    isCurrency = false,
}: {
    label: string;
    value: number;
    isCurrency?: boolean;
}) {
    return (
        <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
            <p className="text-xs font-medium text-gray-500 mb-1">{label}</p>
            <p className="text-lg font-semibold text-gray-900 tabular-nums">
                {isCurrency ? formatCurrency(value) : value.toLocaleString()}
            </p>
        </div>
    );
}

export default function SalesReportContent({
    data,
    loading = false,
    headerInfo,
}: Readonly<SalesReportContentProps>) {
    if (loading) {
        return (
            <div className="py-8">
                <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-4 mb-8">
                    {Array.from({ length: 10 }).map((_, i) => (
                        <div
                            key={i}
                            className="h-20 bg-gray-100 rounded-lg animate-pulse"
                        />
                    ))}
                </div>
                <div className="h-64 bg-gray-100 rounded animate-pulse" />
            </div>
        );
    }

    if (!data) {
        return null;
    }

    const s = data.summary;

    return (
        <div className="py-8 max-w-full mx-auto">
            <div className="flex flex-col items-center mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    Sales Report
                </h2>
                {headerInfo && (
                    <>
                        {headerInfo.hotelName ? (
                            <p className="text-sm text-gray-600 mb-1">
                                {headerInfo.hotelName}
                            </p>
                        ) : null}
                        <p className="text-sm text-gray-500 mb-1">
                            Printed at: {headerInfo.printedAt}
                        </p>
                        <p className="text-sm text-gray-500 mb-1">
                            Report period: {headerInfo.dateRange}
                        </p>
                        <p className="text-sm text-gray-500 mb-1">
                            Room type: {headerInfo.roomType} · Room:{' '}
                            {headerInfo.room}
                        </p>
                        <p className="text-sm text-gray-500 mb-1">
                            Source: {headerInfo.source} · Status:{' '}
                            {headerInfo.status}
                            {headerInfo.inHouseOnly ? ' · In-house only' : ''}
                        </p>
                        <p className="text-sm text-gray-500 mb-1">
                            User: {headerInfo.user}
                        </p>
                        <p className="text-sm text-gray-500">
                            Generated by: {headerInfo.generatedBy} ·{' '}
                            {headerInfo.generatedAt}
                        </p>
                    </>
                )}
            </div>

            <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-4 mb-4">
                <KpiCard
                    label="Total payments received"
                    value={s.totalPaymentsReceived}
                    isCurrency
                />
                <KpiCard
                    label="Expected room revenue"
                    value={s.expectedRoomRevenue}
                    isCurrency
                />
                <KpiCard label="Checked-out count" value={s.checkedOutCount} />
                <KpiCard
                    label="Realised room revenue"
                    value={s.realisedRoomRevenue}
                    isCurrency
                />
                <KpiCard
                    label="Outstanding balance / AR"
                    value={s.outstandingAr}
                    isCurrency
                />
            </div>
            <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-4 mb-8">
                <KpiCard
                    label="Account payable"
                    value={s.totalAccountsPayable}
                    isCurrency
                />
                <KpiCard label="Total bookings" value={s.totalBookings} />
                <KpiCard label="In-house count" value={s.inHouseCount} />
                <KpiCard label="F&B revenue" value={s.fbRevenue} isCurrency />
                <KpiCard
                    label="Total discounts"
                    value={s.totalDiscounts}
                    isCurrency
                />
            </div>

            <div className="overflow-x-auto rounded-lg">
                <table className="w-full border-collapse rounded-lg overflow-hidden min-w-[1100px]">
                    <thead>
                        <tr className="bg-[#F4F4F4]">
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Res. No
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Room / type
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Guest name
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Arrival
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Departure
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Status
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Nights (period)
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Pax
                            </th>
                            <th className="text-left py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                User
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Original rate
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Discount
                            </th>
                            <th className="text-right py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]">
                                Discount total
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.items.map((item, index) => (
                            <tr
                                key={item.reservationNo + index}
                                className="border-b border-gray-100 hover:bg-gray-50"
                            >
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.reservationNo}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.roomNumType}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.guestName}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.arrivalDate}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.departureDate}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.status}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right">
                                    {item.nightsInPeriod}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right">
                                    {item.pax}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878]">
                                    {item.user}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right">
                                    {formatCurrency(item.originalRate)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right">
                                    {item.discount > 0
                                        ? `-${formatCurrency(item.discount)}`
                                        : formatCurrency(0)}
                                </td>
                                <td className="py-4 px-2 text-[14px] text-[#7B7878] text-right">
                                    {item.discountTotal > 0
                                        ? `-${formatCurrency(item.discountTotal)}`
                                        : formatCurrency(0)}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {data.items.length === 0 && (
                <div className="text-center py-12 text-gray-500">
                    No reservations found for the selected filters.
                </div>
            )}
        </div>
    );
}
