import { NightAuditReportData } from './types';

export function generateDummyReportData(): NightAuditReportData {
    return {
        stats: {
            totalRoomsInProperty: 50,
            roomsSold: 32,
            roomsAvailableToday: 47,
            complimentaryHouseUse: 2,
            earlyCheckouts: 1,
            noShows: 3,
            complimentaryHouseUse2: 2,
            occupancy: '68.09%',
        },
        stayingOverGuests: [
            {
                room: '101 – S...',
                guestName: 'Mr. Albert...',
                mobile: '0908976...',
                arrivalDate: '2026-01-15',
                departureDate: '2026-01-17',
                noNights: 5,
                pax: '1/0',
                resNo: 'R-1452',
                source: 'Direct',
                folioNo: 'F-2201',
                total: 120000,
                paid: 80000,
                balance: 40000,
            },
            {
                room: '102 – S...',
                guestName: 'Gift Oluchi',
                mobile: '0708976...',
                arrivalDate: '2026-01-15...',
                departureDate: '2026-01-17',
                noNights: 3,
                pax: '2/1',
                resNo: 'R-1457',
                source: 'Walk-in',
                folioNo: 'F-2206',
                total: 45000,
                paid: 45000,
                balance: 0,
            },
            {
                room: '103 – S...',
                guestName: 'Renee Oga',
                mobile: '0908976...',
                arrivalDate: '2026-01-15...',
                departureDate: '2026-01-17',
                noNights: 2,
                pax: '1/0',
                resNo: 'R-1439',
                source: 'Booki...',
                folioNo: 'F-2205',
                total: 50000,
                paid: 70000,
                balance: -20000,
            },
            {
                room: '105 – S...',
                guestName: 'Tobia Em...',
                mobile: '0808976...',
                arrivalDate: '2026-01-15...',
                departureDate: '2026-01-17',
                noNights: 1,
                pax: '3/2',
                resNo: 'R-1434',
                source: 'Walk-in',
                folioNo: 'F-2203',
                total: 120000,
                paid: 180000,
                balance: -60000,
            },
        ],
        departingGuests: [
            {
                room: '101 – Suite / Deluxe',
                guestName: 'Mr. Albert Rimes',
                arrivalDate: '2026-01-15',
                departureDate: '2026-01-17',
                noNights: 5,
                pax: '1/0',
                resNo: 'R-1452',
                source: 'Direct',
            },
            {
                room: '102 – Suite / Deluxe',
                guestName: 'Gift Oluchi',
                arrivalDate: '2026-01-15...',
                departureDate: '2026-01-17',
                noNights: 3,
                pax: '2/1',
                resNo: 'R-1457',
                source: 'Walk-in',
            },
            {
                room: '103 – Suite / Deluxe',
                guestName: 'Renee Oga',
                arrivalDate: '2026-01-15...',
                departureDate: '2026-01-17',
                noNights: 2,
                pax: '1/0',
                resNo: 'R-1439',
                source: 'Booki...',
            },
            {
                room: '105 – Suite / Deluxe',
                guestName: 'Tobia Emma',
                arrivalDate: '2026-01-15...',
                departureDate: '2026-01-17',
                noNights: 1,
                pax: '3/2',
                resNo: 'R-1434',
                source: 'Walk-in',
            },
        ],
        roomRevenue: [
            {
                room: '101 – Suite / Deluxe',
                noNights: 5,
                rate: 40000,
                amount: 40000,
                paymentMode: 'City Ledger',
                status: 'Pending',
            },
            {
                room: '102 – Suite / Deluxe',
                noNights: 3,
                rate: 45000,
                amount: 45000,
                paymentMode: 'POS',
                status: 'Paid',
            },
            {
                room: '103 – Suite / Deluxe',
                noNights: 2,
                rate: 30000,
                amount: 30000,
                paymentMode: 'Cash',
                status: 'Booki...',
            },
        ],
        foodBeverageCharges: [
            {
                source: '101 – Suite / Deluxe',
                item: 'Grilled Chicken',
                quantity: 3,
                amount: 40000,
                paymentMode: 'City Ledger',
                paid: 'yes',
            },
            {
                source: '102 – Suite / Deluxe',
                item: 'Soft Drink, Milk, Holandia',
                quantity: 4,
                amount: 45000,
                paymentMode: 'POS',
                paid: 'No',
            },
            {
                source: '103 – Suite / Deluxe',
                item: 'Jollof Rice',
                quantity: 1,
                amount: 30000,
                paymentMode: 'Cash',
                paid: 'Yes',
            },
        ],
        roomServices: [
            {
                room: '101 – Suite / Deluxe',
                service: 'Washing & Ironing',
                quantity: 3,
                amount: 40000,
                paymentMode: 'City Ledger',
                paid: 'yes',
            },
            {
                room: '102 – Suite / Deluxe',
                service: 'Ironing Only',
                quantity: 4,
                amount: 45000,
                paymentMode: 'POS',
                paid: 'No',
            },
        ],
        paymentSummary: [
            { paymentMethod: 'City Ledger', amount: 40000 },
            { paymentMethod: 'POS', amount: 45000 },
            { paymentMethod: 'Credit Card', amount: 30000 },
            { paymentMethod: 'Online Payment', amount: 30000 },
            { paymentMethod: 'TOTAL COLLECTED', amount: 316000 },
        ],
        discountsVoids: [
            { type: 'Discounts', count: 3, amount: 40000 },
            { type: 'Voided Transactions', count: 4, amount: 45000 },
            { type: 'Complimentary Charges', count: 2, amount: 30000 },
        ],
        revenueSummary: [
            { description: 'Room Revenue', amount: 485000 },
            { description: 'F&B Revenue', amount: 58500 },
            { description: 'Service Revenue', amount: 92000 },
            { description: 'Other Revenue', amount: 12000 },
            { description: 'Total Revenue', amount: 647500 },
        ],
        outstandingCredits: [
            { description: 'Total Outstanding Balance', value: 65000 },
            { description: 'City Ledger', value: 120000 },
            { description: 'Credit Deposits', value: 85000 },
        ],
        generatedAt: new Date().toISOString(),
        generatedBy: 'Anli Demo Owner',
    };
}
