'use client';

import { formatCurrency } from '@/lib/utils';
import { cn } from '@/lib/utils';
import {
    BanquetReportColumn,
    BanquetReportData,
    BanquetReportHeaderInfo,
    BanquetSummaryCard,
} from '../types';

interface BanquetReportContentProps {
    title: string;
    columns: BanquetReportColumn[];
    summaryCards: BanquetSummaryCard[];
    data: BanquetReportData | null;
    loading?: boolean;
    headerInfo?: BanquetReportHeaderInfo;
}

function formatSummaryValue(
    value: number,
    card: BanquetSummaryCard,
): string {
    if (card.isCurrency) return formatCurrency(value);
    if (card.isPercent) return `${value}%`;
    return value.toLocaleString();
}

function formatCellValue(value: string | number | undefined): string {
    if (value === undefined || value === null) return '—';
    return String(value);
}

export default function BanquetReportContent({
    title,
    columns,
    summaryCards,
    data,
    loading = false,
    headerInfo,
}: Readonly<BanquetReportContentProps>) {
    if (loading) {
        return (
            <div className="py-8">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                    {Array.from({ length: Math.min(summaryCards.length, 4) }).map(
                        (_, i) => (
                            <div
                                key={i}
                                className="h-20 bg-gray-100 rounded-lg animate-pulse"
                            />
                        ),
                    )}
                </div>
                <div className="h-64 bg-gray-100 rounded animate-pulse" />
            </div>
        );
    }

    if (!data) return null;

    return (
        <div className="py-8 max-w-full mx-auto">
            <div className="flex flex-col items-center mb-8 text-center px-2">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    {title}
                </h2>
                {headerInfo ? (
                    <>
                        {headerInfo.hotelName ? (
                            <p className="text-sm text-gray-600 mb-1">
                                {headerInfo.hotelName}
                            </p>
                        ) : null}
                        <p className="text-sm text-gray-500 mb-1">
                            Printed at: {headerInfo.printedAt}
                        </p>
                        <p className="text-sm text-gray-500 mb-1">
                            Report period: {headerInfo.dateRange}
                        </p>
                        <p className="text-sm text-gray-500 mb-1">
                            {headerInfo.filterSummary}
                        </p>
                        <p className="text-sm text-gray-500">
                            Generated by: {headerInfo.generatedBy} ·{' '}
                            {headerInfo.generatedAt}
                        </p>
                    </>
                ) : null}
            </div>

            {summaryCards.length > 0 ? (
                <div
                    className={cn(
                        'grid gap-4 mb-8',
                        summaryCards.length <= 4
                            ? 'grid-cols-2 md:grid-cols-4'
                            : 'grid-cols-2 md:grid-cols-3 xl:grid-cols-5',
                    )}
                >
                    {summaryCards.map((card) => (
                        <div
                            key={card.key}
                            className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm"
                        >
                            <p className="text-xs font-medium text-gray-500 mb-1">
                                {card.label}
                            </p>
                            <p className="text-lg font-semibold text-gray-900 tabular-nums">
                                {formatSummaryValue(
                                    data.summary[card.key] ?? 0,
                                    card,
                                )}
                            </p>
                        </div>
                    ))}
                </div>
            ) : null}

            <div className="overflow-x-auto rounded-lg">
                <table className="w-full border-collapse rounded-lg overflow-hidden min-w-[900px]">
                    <thead>
                        <tr className="bg-[#F4F4F4]">
                            {columns.map((col) => (
                                <th
                                    key={col.key}
                                    className={cn(
                                        'py-3 px-2 text-[14px] font-semibold text-[#0A0A0A]',
                                        col.align === 'right'
                                            ? 'text-right'
                                            : col.align === 'center'
                                              ? 'text-center'
                                              : 'text-left',
                                    )}
                                >
                                    {col.label}
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {data.items.map((row, index) => (
                            <tr
                                key={`${index}-${String(row[columns[0]?.key] ?? index)}`}
                                className="border-b border-gray-100 hover:bg-gray-50"
                            >
                                {columns.map((col) => (
                                    <td
                                        key={col.key}
                                        className={cn(
                                            'py-4 px-2 text-[14px] text-[#7B7878]',
                                            col.align === 'right'
                                                ? 'text-right'
                                                : col.align === 'center'
                                                  ? 'text-center'
                                                  : 'text-left',
                                        )}
                                    >
                                        {formatCellValue(
                                            row[col.key] as
                                                | string
                                                | number
                                                | undefined,
                                        )}
                                    </td>
                                ))}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {data.items.length === 0 ? (
                <div className="text-center py-12 text-gray-500">
                    No records found for the selected filters.
                </div>
            ) : null}
        </div>
    );
}
