'use client';

import type { AdrContributorsResult, AdrSnapshot } from '@/app/actions/guest';
import { Button } from '@/components/ui/button';
import { ChevronLeft, ChevronRight } from 'lucide-react';

interface AdrReportContentProps {
    data: AdrSnapshot | null;
    loading?: boolean;
    headerInfo?: {
        hotelName?: string;
        printedAt: string;
        reportPeriod: string;
        generatedBy: string;
    };
    contributors?: AdrContributorsResult | null;
    contributorsLoading?: boolean;
    onContributorsPageChange?: (page: number) => void;
}

function formatMoney(n: number): string {
    return n.toLocaleString('en-NG', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    });
}

export default function AdrReportContent({
    data,
    loading = false,
    headerInfo,
    contributors = null,
    contributorsLoading = false,
    onContributorsPageChange,
}: Readonly<AdrReportContentProps>) {
    if (loading) {
        return (
            <div className="py-8 max-w-6xl mx-auto w-full px-2">
                <div className="h-8 w-64 bg-slate-100 rounded animate-pulse mb-2 mx-auto" />
                <div className="h-4 w-96 max-w-full bg-slate-100 rounded animate-pulse mb-8 mx-auto" />
                <div className="h-64 bg-slate-100 rounded-xl animate-pulse" />
            </div>
        );
    }

    if (!data) return null;

    const sellableCount =
        data.sellableRoomCount ?? data.context?.sellableRoomCount ?? 0;

    return (
        <div className="py-8 max-w-6xl mx-auto w-full px-2">
            <div className="flex flex-col items-center mb-8 text-center px-2">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    ADR report
                </h2>
                {headerInfo && (
                    <>
                        {headerInfo.hotelName && (
                            <p className="text-sm text-gray-600 mb-1">
                                {headerInfo.hotelName}
                            </p>
                        )}
                        <p className="text-sm text-gray-500 max-w-4xl leading-relaxed">
                            Printed at: {headerInfo.printedAt}
                            {' · '}
                            Report period: {headerInfo.reportPeriod}
                            {' · '}
                            Generated by: {headerInfo.generatedBy}
                        </p>
                    </>
                )}
            </div>

            <div className="mb-8 grid grid-cols-1 sm:grid-cols-5 gap-4">
                <div className="rounded-xl border border-slate-200 bg-white px-4 py-4 text-center shadow-sm">
                    <div className="text-xs font-medium text-slate-500 uppercase tracking-wide">
                        Guest-nights
                    </div>
                    <div className="text-xl font-bold text-slate-900 mt-1 tabular-nums">
                        {data.roomsSoldNights}
                    </div>
                </div>
                <div className="rounded-xl border border-slate-200 bg-white px-4 py-4 text-center shadow-sm">
                    <div className="text-xs font-medium text-slate-500 uppercase tracking-wide">
                        Total room revenue
                    </div>
                    <div className="text-xl font-bold text-slate-900 mt-1 tabular-nums">
                        {formatMoney(data.totalRoomRevenue)}
                    </div>
                </div>
                <div className="rounded-xl border border-violet-600/25 bg-violet-50/10 px-4 py-4 text-center shadow-sm">
                    <div className="text-xs font-medium text-slate-500 uppercase tracking-wide">
                        Occupancy %
                    </div>
                    <div className="text-xl font-bold text-violet-700 mt-1 tabular-nums">
                        {(sellableCount > 0
                            ? (data.roomsSoldNights /
                                  (sellableCount * (data.byDay.length || 1))) *
                              100
                            : 0
                        ).toFixed(1)}
                        %
                    </div>
                </div>
                <div className="rounded-xl border border-orion-blue/25 bg-orion-blue/5 px-4 py-4 text-center shadow-sm">
                    <div className="text-xs font-medium text-slate-500 uppercase tracking-wide">
                        ADR (blended)
                    </div>
                    <div className="text-xl font-bold text-orion-blue mt-1 tabular-nums">
                        {formatMoney(data.adr)}
                    </div>
                </div>
                <div className="rounded-xl border border-emerald-600/25 bg-emerald-50/10 px-4 py-4 text-center shadow-sm">
                    <div className="text-xs font-medium text-slate-500 uppercase tracking-wide">
                        RevPAR (blended)
                    </div>
                    <div className="text-xl font-bold text-emerald-700 mt-1 tabular-nums">
                        {formatMoney(
                            sellableCount > 0
                                ? data.totalRoomRevenue / sellableCount
                                : 0,
                        )}
                    </div>
                </div>
            </div>

            {data.context ? (
                <div className="mb-8 rounded-xl border border-slate-200 bg-slate-50/90 px-5 py-4 text-sm text-slate-700 shadow-sm">
                    <div className="font-semibold text-gray-900 mb-2">
                        Day context ({data.from})
                    </div>
                    <ul className="space-y-1.5">
                        <li>
                            Sellable rooms:{' '}
                            <span className="font-medium text-gray-900">
                                {data.context.sellableRoomCount}
                            </span>
                        </li>
                        <li>
                            Guest-nights (this night):{' '}
                            <span className="font-medium text-gray-900">
                                {data.context.dayGuestNights}
                            </span>
                        </li>
                        {data.context.occupancyPercent != null ? (
                            <li>
                                Approx. occupancy:{' '}
                                <span className="font-medium text-gray-900">
                                    {data.context.occupancyPercent}%
                                </span>
                            </li>
                        ) : null}
                        <li>
                            Suggested minimum rate:{' '}
                            <span className="font-medium text-gray-900">
                                {formatMoney(data.context.suggestedMinRate)}
                            </span>
                        </li>
                        {data.context.targetAdr != null ? (
                            <li>
                                Target ADR:{' '}
                                <span className="font-medium text-gray-900">
                                    {formatMoney(data.context.targetAdr)}
                                </span>
                                {data.context.vsTargetPercent != null ? (
                                    <span
                                        className={
                                            data.context.band === 'up'
                                                ? ' text-green-700'
                                                : data.context.band === 'down'
                                                  ? ' text-red-700'
                                                  : ' text-gray-600'
                                        }
                                    >
                                        {' '}
                                        (
                                        {data.context.vsTargetPercent > 0
                                            ? '+'
                                            : ''}
                                        {data.context.vsTargetPercent}% vs
                                        target)
                                    </span>
                                ) : null}
                            </li>
                        ) : null}
                        {data.context.minRateFactorApplied != null ? (
                            <li>
                                Min-rate factor applied:{' '}
                                <span className="font-medium text-gray-900">
                                    {data.context.minRateFactorApplied}
                                </span>
                            </li>
                        ) : null}
                        {data.context.maxDiscountPercentFrontDesk != null ? (
                            <li>
                                Front-desk ADR-move hint: warn past ~{' '}
                                <span className="font-medium text-gray-900">
                                    {data.context.maxDiscountPercentFrontDesk}%
                                </span>{' '}
                                drop vs current ADR (what-if / desk guidance).
                            </li>
                        ) : null}
                        {data.context.priorDayAdr != null ? (
                            <li>
                                Prior day ADR:{' '}
                                <span className="font-medium text-gray-900">
                                    {formatMoney(data.context.priorDayAdr)}
                                </span>
                                {data.context.vsPriorDayPercent != null ? (
                                    <span
                                        className={
                                            data.context.band === 'up'
                                                ? ' text-green-700'
                                                : data.context.band === 'down'
                                                  ? ' text-red-700'
                                                  : ' text-gray-600'
                                        }
                                    >
                                        {' '}
                                        (
                                        {data.context.vsPriorDayPercent > 0
                                            ? '+'
                                            : ''}
                                        {data.context.vsPriorDayPercent}% vs
                                        prior)
                                    </span>
                                ) : null}
                            </li>
                        ) : null}
                    </ul>
                </div>
            ) : null}

            <div className="overflow-x-auto rounded-xl border border-slate-200 shadow-sm">
                <table className="w-full border-collapse min-w-[520px]">
                    <thead>
                        <tr className="bg-slate-50 border-b border-slate-200">
                            <th className="text-left py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                Date
                            </th>
                            <th className="text-right py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                Guest-nights
                            </th>
                            <th className="text-right py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                Occupancy %
                            </th>
                            <th className="text-right py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                Room revenue
                            </th>
                            <th className="text-right py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                ADR
                            </th>
                            <th className="text-right py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                RevPAR
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.byDay.map((row) => (
                            <tr
                                key={row.date}
                                className="border-b border-slate-100 last:border-0 hover:bg-slate-50/80"
                            >
                                <td className="py-3.5 px-4 text-sm text-slate-700">
                                    {row.date}
                                </td>
                                <td className="py-3.5 px-4 text-sm text-slate-700 text-right tabular-nums">
                                    {row.roomsSoldNights}
                                </td>
                                <td className="py-3.5 px-4 text-sm font-medium text-violet-700 text-right tabular-nums">
                                    {(sellableCount > 0
                                        ? (row.roomsSoldNights /
                                              sellableCount) *
                                          100
                                        : 0
                                    ).toFixed(1)}
                                    %
                                </td>
                                <td className="py-3.5 px-4 text-sm text-slate-700 text-right tabular-nums">
                                    {formatMoney(row.totalRoomRevenue)}
                                </td>
                                <td className="py-3.5 px-4 text-sm font-medium text-slate-900 text-right tabular-nums">
                                    {formatMoney(row.adr)}
                                </td>
                                <td className="py-3.5 px-4 text-sm font-medium text-emerald-700 text-right tabular-nums">
                                    {formatMoney(
                                        sellableCount > 0
                                            ? row.totalRoomRevenue /
                                                  sellableCount
                                            : 0,
                                    )}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {data.byDay.length === 0 && (
                <div className="text-center py-12 text-gray-500">
                    No guest-nights in range for the selected filters.
                </div>
            )}

            {data.byDay.length > 0 && headerInfo && (
                <>
                    <p className="text-center text-sm text-gray-500 mt-6 max-w-3xl mx-auto leading-relaxed">
                        {data.definition}
                    </p>
                    <p className="text-center text-sm text-orange-600 mt-4">
                        Generated {headerInfo.printedAt} · Created by{' '}
                        {headerInfo.generatedBy}
                    </p>
                </>
            )}

            {contributors != null && contributors.total > 0 && (
                <div className="mt-12">
                    <h3 className="text-lg font-semibold text-slate-900 mb-2 text-center">
                        Contributing stays
                    </h3>
                    <p className="text-sm text-slate-500 text-center mb-5 max-w-xl mx-auto">
                        Stays ranked by room revenue attributed to this period
                        (same rules as the ADR above).
                    </p>
                    <div className="relative overflow-x-auto rounded-xl border border-slate-200 shadow-sm">
                        {contributorsLoading && (
                            <div className="absolute inset-0 z-10 flex items-center justify-center bg-white/60 rounded-lg">
                                <span className="text-sm text-gray-600">
                                    Loading…
                                </span>
                            </div>
                        )}
                        <table className="w-full border-collapse min-w-[720px]">
                            <thead>
                                <tr className="bg-slate-50 border-b border-slate-200">
                                    <th className="text-left py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                        Booking
                                    </th>
                                    <th className="text-left py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                        Guest
                                    </th>
                                    <th className="text-left py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                        Room
                                    </th>
                                    <th className="text-left py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                        Type
                                    </th>
                                    <th className="text-left py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                        Status
                                    </th>
                                    <th className="text-right py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                        Nights
                                    </th>
                                    <th className="text-right py-3 px-4 text-xs font-semibold text-slate-600 uppercase tracking-wide">
                                        Room revenue
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {contributors.items.map((row) => (
                                    <tr
                                        key={row.guestId}
                                        className="border-b border-slate-100 last:border-0 hover:bg-slate-50/80"
                                    >
                                        <td className="py-3 px-4 text-sm text-slate-700">
                                            {row.bookingCode ?? '—'}
                                        </td>
                                        <td className="py-3 px-4 text-sm text-slate-700">
                                            {row.guestName ?? '—'}
                                        </td>
                                        <td className="py-3 px-4 text-sm text-slate-700">
                                            {row.roomNumber ?? '—'}
                                        </td>
                                        <td className="py-3 px-4 text-sm text-slate-700">
                                            {row.roomTypeName ?? '—'}
                                        </td>
                                        <td className="py-3 px-4 text-sm text-slate-700">
                                            {row.bookingStatus}
                                        </td>
                                        <td className="py-3 px-4 text-sm text-slate-700 text-right tabular-nums">
                                            {row.guestNights}
                                        </td>
                                        <td className="py-3 px-4 text-sm text-slate-700 text-right tabular-nums">
                                            {formatMoney(row.roomRevenue)}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                    {onContributorsPageChange &&
                        contributors.limit > 0 &&
                        contributors.total > contributors.limit && (
                            <div className="flex flex-wrap items-center justify-center gap-3 mt-4">
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    disabled={
                                        contributorsLoading ||
                                        contributors.page <= 1
                                    }
                                    onClick={() =>
                                        onContributorsPageChange(
                                            contributors.page - 1,
                                        )
                                    }
                                    className="gap-1"
                                >
                                    <ChevronLeft className="h-4 w-4" />
                                    Previous
                                </Button>
                                <span className="text-sm text-gray-600">
                                    Page {contributors.page} of{' '}
                                    {Math.ceil(
                                        contributors.total / contributors.limit,
                                    )}{' '}
                                    · {contributors.total} stays
                                </span>
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    disabled={
                                        contributorsLoading ||
                                        contributors.page *
                                            contributors.limit >=
                                            contributors.total
                                    }
                                    onClick={() =>
                                        onContributorsPageChange(
                                            contributors.page + 1,
                                        )
                                    }
                                    className="gap-1"
                                >
                                    Next
                                    <ChevronRight className="h-4 w-4" />
                                </Button>
                            </div>
                        )}
                </div>
            )}

            {contributors?.total === 0 && (
                <div className="mt-10 text-center text-sm text-gray-500">
                    No contributing stays for this period with the current
                    filters.
                </div>
            )}
        </div>
    );
}
