import { FormDataType } from './types';

export const defaultFormData: Partial<FormDataType> = {
    roomtype: 0,
    startDate: '',
    endDate: '',
    startTime: '',
    endTime: '',
    fullName: '',
    phoneNumber: '',
    numberOfGuests: 1,
    email: '',
    secondGuestFullName: '',
    secondGuestPhoneNumber: '',
    secondGuestType: 'adult',
    paymentMethod: '',
    amountPaid: 0,
    outstanding: 0,
    receivingAccount: '',
    nights: 0,
    roomNumber: '',
    quotationRooms: [],
    isComplimentary: false,
    isVoid: false,
    discountType: undefined,
    discountValue: undefined,
    discountReason: '',
    voidReason: '',
    gender: '',
    dateOfBirth: '',
    nationality: '',
    address: '',
    purposeOfVisit: '',
    loyaltyTier: '',
    loyaltyPoints: undefined,
    eligibleForReward: undefined,
    birthday: '',
    feedbackNotes: '',
    customerType: '',
    emailConsent: undefined,
    preferredContactMethod: '',
};
